config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :oauth do 
      collection do
        post :auth
        get :callback
        get :continue_callback
        post :get_campaign_info
        post :refresh_token
      end
    end

    root "oauth#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  before_action :set_auth_client
  
  def new
    @code_verifier = SecureRandom.hex(22)
    @code_challenge = Base64.urlsafe_encode64(Digest::SHA256.digest(@code_verifier), padding: false)
  end

  def auth
    # Step 1: Generate Authentication URl
    auth_url = @client.auth_code.authorize_url(redirect_uri: ENV['APP_CALLBACK_URI'], scope: "read", code_challenge: params[:code_challenge], code_challenge_method: "S256")
    
    ####### resulting url #######
    # http://localhost:3000/oauth/authorize?client_id=uY9cxCR_KBcH7PGaCVFkPZ8hhVqv3DdFd5g0ciLZ6dI
    # &code_challenge=444a545674bfdc7e13a64fc5a30760a5&code_challenge_method=plain&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Foauth%2Fcallback
    # &response_type=code&scope=read+write
    ####### resulting url #######

    session[:code_verifier] = params[:code_verifier]
    
    # Step 2 (1st handshake): Redirect to server login page to generate access_token against user session and get code
    redirect_to auth_url
  end

  def callback
    # Step 3: Backend call (2nd handshake) to Auth server to get access_token (jwt), additional request params include `code` received at Step 2
    # and `code_verifier` which will be verified by the auth server
    @token = @client.auth_code.get_token(params[:code], redirect_uri: ENV['APP_CALLBACK_URI'], code_verifier: session[:code_verifier])
    @token_payload = JWT.decode @token.token, nil, false
  end

  def continue_callback
    # Step 3: Backend call (2nd handshake) to Auth server to get access_token (jwt), additional request params include `code` received at Step 2
    # and `code_verifier` which will be verified by the auth server
    @token = @client.auth_code.get_token(params[:code], redirect_uri: ENV['APP_CALLBACK_URI'], code_verifier: session[:code_verifier])
    @token_payload = JWT.decode @token.token, nil, false
  end



  def refresh_token
    url = URI(ENV['AUTH_SERVER_URL']+"/oauth/token")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true if url.instance_of? URI::HTTPS

    request = Net::HTTP::Post.new(url)
    request["content-type"] = 'application/x-www-form-urlencoded'
    request["cache-control"] = 'no-cache'
    request.body = "grant_type=refresh_token&refresh_token=#{params[:refresh_token]}&client_id=#{ENV['APP_ID']}&client_secret=#{ENV['APP_SECRET']}"

    response = http.request(request)
    @data = response.read_body
  end

  def get_campaign_info
    # URI of trader server
    url = URI(ENV['AUTH_SERVER_URL']+"/api/graphql")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true if url.instance_of? URI::HTTPS

    request = Net::HTTP::Post.new(url)
    request["authorization"] = "Bearer #{params[:token]}"
    request["content-type"] = 'application/json'

    # GraphQL query string
    request.body = grapqhl_query
    response = http.request(request)
    @data = response.read_body
  end 

  private

  def set_auth_client
    # Step 0: Setup OAuth client with App ID, App Secret registered in Auth server and `site` url of Auth searver
    @client = OAuth2::Client.new(ENV['APP_ID'], ENV['APP_SECRET'], site: ENV['AUTH_SERVER_URL'])
  end

  def permit_params
    params.permit!
  end

  def grapqhl_query
    "{     \"operationName\":\"GetCampaigns\",     \"variables\":{},     
      \"query\":
        \"query GetCampaigns 
          {\ 
            campaigns 
            { 
              data 
              {
                id
                name
                state
                life_stage
                start_at
                end_at
                bid_tactic
              }  
              __typename\ 
            }
          \\n}
        \\n\"   
      }"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OauthClientApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <style>
    .gradient-custom-2 {
    /* fallback for old browsers */
    background: #fccb90;

    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);

    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
    }

    @media (min-width: 768px) {
    .gradient-form {
    height: 100vh !important;
    }
    }
    @media (min-width: 769px) {
    .gradient-custom-2 {
    border-top-right-radius: .3rem;
    border-bottom-right-radius: .3rem;
    }
    }
    </style>
  </body>

</html>

app/views/oauth/callback.html.erb
<div class="text-center pt-1 mb-5 pb-1">
  <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3"><h1>Successfully Logged In</h1></button>
</div>
<b>JWT Token Received:</b> <span style="color: red;"><%= @token.token %></span>
</br>
</br>
<b>JWT Token Payload:</b> <span style="color: green;"><pre><%= JSON.pretty_generate(@token_payload[0]) %></pre></span>
</br>
<b>JWT Token Header:</b> <span style="color: green;"><pre><%= JSON.pretty_generate(@token_payload[1]) %></pre></span>
</br>
<b>JWT Refresh Token:</b> <span style="color: blue;"><%= @token.refresh_token %></span>
</br>
</br>
</br>

<%= form_with url: get_campaign_info_oauth_index_url, method: :post, style: 'text-align: center;' do |form| %>
  <%= form.text_field :token, value: @token.token, hidden: true, size: "30" %>
  
  <div class="text-center pt-1 mb-5 pb-1">

    <%= form.submit "Get my campaigns from Samsung DSP", class: "btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" %>
  </div>

<% end %>

app/views/oauth/continue_callback.html.erb
<div class="text-center pt-1 mb-5 pb-1">
  <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3"><h1>Successfully Logged In</h1></button>
</div>
<b>JWT Token Received:</b> <span style="color: red;"><%= @token.token %></span>
</br>
</br>
<b>JWT Token Payload:</b> <span style="color: green;"><pre><%= JSON.pretty_generate(@token_payload[0]) %></pre></span>
</br>
<b>JWT Token Header:</b> <span style="color: green;"><pre><%= JSON.pretty_generate(@token_payload[1]) %></pre></span>
</br>
<b>JWT Refresh Token:</b> <span style="color: blue;"><%= @token.refresh_token %></span>
</br>
</br>
</br>

<%= form_with url: get_campaign_info_oauth_index_url, method: :post, style: 'text-align: center;' do |form| %>
  <%= form.text_field :token, value: @token.token, hidden: true, size: "30" %>
  
  <div class="text-center pt-1 mb-5 pb-1">

    <%= form.submit "Get my campaigns from Samsung DSP", class: "btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" %>
  </div>

<% end %>

app/views/oauth/get_campaign_info.html.erb
<h1>My Campaigns (Query Result)</h1>

<h4>Request Headers</h4>
<pre><%= JSON.pretty_generate({authorization: "Bearer #{params[:token]}", content_type: 'application/json'}) %></pre>
<br>
<h4>Response Body</h4>
<pre><%= JSON.pretty_generate(JSON.parse(@data)) %></pre>

app/views/oauth/new.html.erb
<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center">
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                    style="width: 185px;" alt="logo">
                  <h4 class="mt-1 mb-5 pb-1">Campaign Dashboard App</h4>
                </div>

                <%= form_with url: auth_oauth_index_url, method: :post, style: 'text-align: center;' do |form| %>
                  <div class="form-outline mb-4">
                    <%= form.label "(code verifier) V = " %>
                    <%= form.text_field :code_verifier, value: @code_verifier, readonly: true, class: "form-control" %>
                  </div>
                  </br>
                  <div class="form-outline mb-4">
                    <%= form.label "(code_challenge) $ = sha256(V) " %>
                    <%= form.text_field :code_challenge, value: @code_challenge, readonly: true, class: "form-control" %>
                  </div>
                  </br>
                  <div class="text-center pt-1 mb-5 pb-1">
                    <%= form.submit "Sign in from Samsung DSP", class: "btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">We are more than just a company</h4>
                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<style>

app/views/oauth/refresh_token.html.erb
<h1>Client App (Refresh Token)</h1>

<h4>Request Body</h4>
<pre><%= JSON.pretty_generate({grant_type: 'refresh_token', refresh_token: "#{params[:refresh_token]}", client_id: "#{ENV['APP_ID']}", client_secret: "#{ENV['APP_SECRET']}"}) %></pre>
<br>
<h4>Response Body</h4>
<pre><%= JSON.pretty_generate(JSON.parse(@data)) %></pre>